# Generated by Django 5.2 on 2025-04-13 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.TextField(max_length='7', null='True')),
                ('pub_date', models.DateTimeField(verbose_name='date wished')),
                ('sound', models.FilePathField(path='media/')),
            ],
        ),
    ]
